title: Open Socialism
tagline: a compelling alternative to democratic capitalism
description: > # this means to ignore newlines until "baseurl:"
  a compelling alternative to democratic capitalism
baseurl: "" # the subpath of your site, e.g. /blog
url: http://opensocialism.com
github_username:  open-socialism
analytics_id: UA-75947611-1
exclude: ["vendor"]
url: https://opensocialism.com

# Build settings
markdown: kramdown

sass:
  sass_dir: _sass
  style: :compressed

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
