version: "2"

services:
  dev:
    build: .
    working_dir: /work
    command: ./run
    volumes:
      - .:/work
      - ruby2.4-gem-cache:/usr/local/bundle
    ports:
      - "4000:4000"
  prod:
    environment:
      - JEKYLL_ENV=production
    extends:
      service: dev

volumes:
  ruby2.4-gem-cache:
    external: true
