# stuck on 2 as we need `extends`. Alternatives seem bad. https://github.com/moby/moby/issues/31101
version: '2'

services:
  dev:
    build:
      dockerfile: support/dev/Dockerfile
      context: .
    command: bash
    working_dir: /work
    volumes:
    - .:/work
    - ruby2.5-gem-cache:/usr/local/bundle

  dev-run:
    extends:
      service: dev
    command: support/dev/run
    ports:
    - 4000:4000

  prod:
    environment:
    - JEKYLL_ENV=production
    extends:
      service: dev-run

  yamllint:
    build: support/yamllint
    command: support/yamllint/run
    volumes:
    - .:/work
    working_dir: /work

volumes:
  ruby2.5-gem-cache:
    external: true
